default: &default
  store_options:
    # Cap age of oldest cache entry to fulfill retention policies
    # max_age: 5184000  # 60 days in seconds
    max_size: 268435456  # 256 megabytes in bytes
    namespace: kojagency

development:
  <<: *default

test:
  <<: *default

production:
  database: cache
  <<: *default
